replicaCount: 1

image:
  repository: chanchaljh/onvif-camera-controller
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

serviceAccount:
  create: false
  name: ""

imagePullSecrets: []

livenessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10